// Package matrix renders conformance summaries of several implementations
// into a single static HTML interop matrix.
package matrix

import (
	"fmt"
	"html/template"
	"strings"

	"github.com/patrikfejda/scim-conformance/internal/check"
	"github.com/patrikfejda/scim-conformance/internal/report"
)

// Entry is one implementation's run.
type Entry struct {
	Name    string
	Summary report.Summary
}

type row struct {
	ID          string
	Description string
	Reference   string
	Severity    check.Severity
	Cells       []cell
}

type cell struct {
	Class  string // pass | fail | skip | error | none
	Label  string
	Detail string
}

var pageTemplate = template.Must(template.New("matrix").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SCIM 2.0 interop matrix</title>
<style>
  body { font: 15px/1.5 system-ui, sans-serif; margin: 2rem auto; max-width: 72rem; padding: 0 1rem; color: #222; }
  h1 { font-size: 1.5rem; }
  table { border-collapse: collapse; width: 100%; font-size: 0.85rem; }
  th, td { border: 1px solid #ccc; padding: 0.35rem 0.5rem; text-align: left; vertical-align: top; }
  th { background: #f2f2f2; }
  .cell { text-align: center; font-weight: 600; }
  .pass { background: #d8f0d8; }
  .fail { background: #f6d6d6; }
  .skip { background: #eee; color: #666; }
  .error { background: #f3e2c0; }
  .none { background: #fafafa; color: #aaa; }
  .sev { color: #666; font-size: 0.75rem; }
  .ref { color: #666; white-space: nowrap; }
  footer { margin-top: 1.5rem; color: #666; font-size: 0.85rem; }
</style>
</head>
<body>
<h1>SCIM 2.0 interop matrix</h1>
<p>Results of <a href="https://github.com/patrikfejda/scim-conformance">scim-conformance</a> runs
against open-source SCIM implementations. <strong>pass</strong>/<strong>fail</strong> per check;
advisory checks record real-world deviations without failing a run. Failure details are shown
in the cell title (hover). Findings write-ups live in
<a href="https://github.com/patrikfejda/scim-conformance/tree/main/docs/findings">docs/findings</a>.</p>
<table>
<thead><tr><th>Check</th><th>Reference</th>{{range .Names}}<th>{{.}}</th>{{end}}</tr></thead>
<tbody>
{{range .Rows}}<tr>
<td><code>{{.ID}}</code><br>{{.Description}} <span class="sev">({{.Severity}})</span></td>
<td class="ref">{{.Reference}}</td>
{{range .Cells}}<td class="cell {{.Class}}"{{if .Detail}} title="{{.Detail}}"{{end}}>{{.Label}}</td>{{end}}
</tr>
{{end}}</tbody>
</table>
<footer>Generated by <code>matrix-gen</code> from JSON reports in
<a href="https://github.com/patrikfejda/scim-conformance/tree/main/docs/matrix">docs/matrix</a>.
Results are point-in-time observations of specific versions, filed upstream before publication.</footer>
</body>
</html>
`))

// RenderHTML builds the matrix page. Check rows follow the order of the
// first entry's results; checks unknown to an implementation render as a
// gap rather than a failure.
func RenderHTML(entries []Entry) (string, error) {
	if len(entries) == 0 {
		return "", fmt.Errorf("no entries to render")
	}
	var rows []row
	seen := map[string]int{}
	for _, e := range entries {
		for _, res := range e.Summary.Results {
			if _, ok := seen[res.ID]; ok {
				continue
			}
			seen[res.ID] = len(rows)
			rows = append(rows, row{ID: res.ID, Description: res.Description, Reference: res.Reference, Severity: res.Severity})
		}
	}
	for i := range rows {
		rows[i].Cells = make([]cell, len(entries))
		for j := range entries {
			rows[i].Cells[j] = cell{Class: "none", Label: "—"}
		}
	}
	for j, e := range entries {
		for _, res := range e.Summary.Results {
			i := seen[res.ID]
			rows[i].Cells[j] = cell{Class: string(res.Status), Label: string(res.Status), Detail: res.Detail}
			if rows[i].Description == "" {
				rows[i].Description = res.Description
			}
		}
	}
	names := make([]string, len(entries))
	for i, e := range entries {
		names[i] = e.Name
	}
	var out strings.Builder
	err := pageTemplate.Execute(&out, map[string]any{"Names": names, "Rows": rows})
	return out.String(), err
}
